site_name: Epikcord.py
site_description: An API Wrapper for Discord's API for Python
repo_url: https://github.com/Jerrydotpy/EpikCordGuide
edit_uri: blob/main/

nav:
  - Home:
    - Overiew: index.md
    - FAQ: faq.md
    - Contributing: contributing.md
  - Getting started:
    - Installing: gettingstarted/installing.md
    - Creating your first bot: gettingstarted/creatingbot.md
    - Sections: gettingstarted/sections.md
  - Guides:
    - User commands: guides/usercommands.md
    - Buttons: guides/buttons.md
    - Message commands: guides/messagecommands.md
    - Slash commands: guides/slashcommands.md
  - Others:
    - Installing Git: others/git.md

theme:
  name: material
  language: en
  features:
    - tabs
    - instant
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - navigation.sections
    - navigation.indexes
    - content.code.annotate
    - navigation.tabs    
  palette: 
    - scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - scheme: slate 
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github
  logo: src/epikcord.png
  favicon: src/epikcord.ico
  features:
      - navigation.instant
      - navigation.tabs
      - navigation.top
      - content.tabs.link
markdown_extensions:
  - pymdownx.highlight:
      linenums: true
  - pymdownx.keys
  - pymdownx.snippets
  - pymdownx.superfences
  - meta
  - attr_list
  - admonition
  - pymdownx.tabbed
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - toc:
      permalink: true
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Epikcord/Epikcord.py

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          rendering:
            show_source: true
